### PR TITLE
Update `selecteph`

### PR DESCRIPTION
**Pull request by LuEdRaMo**
This PR updates the function `selecteph` to cover the functionality of NEOs' [`loadpeeph`](https://github.com/PerezHz/NEOs.jl/blob/c5ce6ec6763a35383f16b999ee0c2dac403b8199/src/observations/jpl_eph.jl#L138), so that we can eventually deprecate the latter.

### CODE REVIEW

**Comment by PerezHz** [comment]
Are there more things you would like to add here @LuEdRaMo, or is this ready for review/merging?

**Comment by LuEdRaMo** [comment]
This is ready, altough I dont know if we should merge this before/after https://github.com/PerezHz/PlanetaryEphemeris.jl/pull/35.

**Comment by PerezHz** [comment]
> This is ready, altough I don't know if we should merge this before/after https://github.com/PerezHz/PlanetaryEphemeris.jl/pull/35.

Good point, I went ahead and merged #35, now maybe you can update this PR and we can merge this afterwards.

**Review by PerezHz — APPROVED** [review]
Again, thanks for this contribution @LuEdRaMo. I would only suggest to add a quick unit test probably after the calls to `propagate` in the tests, just as a quick check on the functionality. Otherwise, LGTM!

**Comment by PerezHz** [comment]
Couple of other points: we should try to update this branch with latest changes in `main`. I would also suggest bumping a patch version (0.8.1).

**Comment by PerezHz** [comment]
Alright, LGTM! Merging! Thanks!

**Pull request merged**
